language: haskell

env:
 - GHCVER=7.8.3
 
before_install:
 - cabal install hpc-coveralls

script:
 - cabal configure --enable-tests --enable-library-coverage && cabal build
 - run-cabal-test 

after_script:
 - hpc-coveralls --exclude-dir=tests gpc-unit-tests
