language: haskell

env:
 - GHCVER=7.8.3
 
install:
 - cabal update
 - cabal install --only-dependencies --enable-tests 
 
script:
 - cabal configure --enable-tests --enable-library-coverage
 - cabal build   
 - cabal test --show-details=always

after_script:
 - cabal install hpc-coveralls
 - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=tests test-all
